# Generated by Django 5.1.15 on 2026-06-22 20:12

import django.core.validators
import django.db.models.deletion
import uuid
import voucher_engine.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, default=voucher_engine.models.generate_voucher_code, editable=False, help_text='Cryptographically secure voucher code (CSPRNG).', max_length=64, unique=True)),
                ('value', models.DecimalField(decimal_places=2, help_text='Original face value of the voucher.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('remaining_value', models.DecimalField(decimal_places=2, help_text='Current remaining balance. Decremented atomically on redemption.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Master switch. False = permanently disabled.')),
                ('is_redeemed', models.BooleanField(db_index=True, default=False, help_text='True when remaining_value reaches zero via redemption.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional hard expiration. Null = never expires.', null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, help_text='Timestamp of full redemption (remaining_value = 0).', null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Timestamp when the voucher was administratively disabled.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary key-value metadata for downstream integrations.')),
                ('created_by', models.ForeignKey(blank=True, help_text='Administrative user who created this voucher.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers_created', to=settings.AUTH_USER_MODEL)),
                ('issued_to', models.ForeignKey(blank=True, help_text='User the voucher was issued to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vtx_voucher',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedemptionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount that was (or was attempted to be) redeemed.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED_INACTIVE', 'Failed — Voucher Inactive'), ('FAILED_REDEEMED', 'Failed — Already Redeemed'), ('FAILED_EXPIRED', 'Failed — Voucher Expired'), ('FAILED_INSUFFICIENT', 'Failed — Insufficient Value'), ('FAILED_CONCURRENCY', 'Failed — Concurrency Conflict')], help_text='Outcome of the redemption attempt.', max_length=24)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP captured at redemption time for forensic audit.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Machine-generated note explaining the outcome.')),
                ('redeemed_by', models.ForeignKey(blank=True, help_text='User who initiated the redemption.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redemptions_performed', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(help_text='The voucher that was targeted for redemption.', on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='voucher_engine.voucher')),
            ],
            options={
                'db_table': 'vtx_redemption_record',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['code'], name='idx_voucher_code'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['is_active', 'is_redeemed'], name='idx_voucher_state'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['expires_at'], name='idx_voucher_expiry'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='chk_voucher_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_value__gte', 0)), name='chk_voucher_remaining_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', False), ('is_redeemed', False), ('deactivated_at__isnull', True), _negated=True), name='chk_voucher_deactivation_consistency'),
        ),
        migrations.AddIndex(
            model_name='redemptionrecord',
            index=models.Index(fields=['voucher', 'redeemed_at'], name='idx_redemption_voucher_time'),
        ),
    ]
